# **Aula 04** - Extração de Características (Features) em Texto

* Parte 1 - Corporas
* Parte 2 - Extração de Características em Texto

## **Parte 1** - Trabalhando com Corporas

### Início do Processamento do Corpus

In [ ]:
def ler(nome_arquivo):
  arquivo = open(nome_arquivo,'r', encoding='utf-8')
  conteudo_arq = arquivo.read()
  arquivo.close()
  return conteudo_arq

In [ ]:
texto = ler('/content/drive/MyDrive/Colab Notebooks/2025.05 Ubirajara.txt')
print(len(texto))

219835


### Primeira Etapa - Buscador de Palavras

In [ ]:
def buscador(alvo, texto):
  texto = texto.replace('\n',' ')
  texto = texto.replace('\t',' ')

  ocorrencias = []

  encontrado_aqui = texto.find(alvo, 0)

  while encontrado_aqui > 0:
    pos_inicial = encontrado_aqui - (40 - len(alvo))
    trecho = texto[pos_inicial: pos_inicial + 80]

    ocorrencias.append(trecho)

    encontrado_aqui = texto.find(alvo, encontrado_aqui + 1)

    return ocorrencias

In [ ]:
resultados = buscador(' peito', texto)

for trecho in resultados:
  print(trecho)

i o chefe tocantim quem recebeu no peito a ponta farpada.  Quando o corpo robust


### Segunda Etapa - Limpeza dos Corpus

In [ ]:
palavras = texto.split()

In [ ]:
def limpar(lista):
  lixo = '.,:;?!"´`^~()[]{}\/|@#$%¨&*-'
  quase_limpo = [x.strip(lixo).lower() for x in lista]
  return [x for x in quase_limpo if x.isalpha() or '-' not in x]

In [ ]:
teste = "Corre-se atrás do carro, corre se o carro for embora."
word = teste.split()
print(word)

['Corre-se', 'atrás', 'do', 'carro,', 'corre', 'se', 'o', 'carro', 'for', 'embora.']


In [ ]:
print(limpar(word))

['atrás', 'do', 'carro', 'corre', 'se', 'o', 'carro', 'for', 'embora']


In [ ]:
print(len(palavras))
palavras = limpar(palavras)
print(len(palavras))

37139
36585


## **Parte 2** - Extração de Características

### Exemplo 1 - Implementando BOW

Criar uma implementação simples de BoW usando CountVectorizer do scikit-learn.

In [ ]:
# importando a ferramenta que irá criar a representação numérica
from sklearn.feature_extraction.text import CountVectorizer

# criando um corpus de documentos que será usado para criação do vocabulário
documentos = [
    "gato e cachorro",
    "gato brinca com cachorro",
    "gato e rato",
    "Cachorro, gato e rato",
    "Gato",
    "Cachorro e rato"
]
# Criando um objeto para ser utilizado: transformar os documentos em vetores
vectorizer = CountVectorizer()

# Criando a matriz de contagem
X = vectorizer.fit_transform(documentos)
  # fit >>> cria um vocabulário das palavras
  # transforme >>> conta a frequencia de cada palavra no corpus

# Imprimindo a Matriz e o Vocabulário gerado
print(f"Vocabulario: {vectorizer.vocabulary_}")
  # realiza o mapeamento do vocabulário para um índice da matriz

print("Matriz BoW:")
print(X.toarray())
  # mostra a frequencia de cada palavra dentro da matriz

Vocabulario: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}
Matriz BoW:
[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]
 [0 1 0 1 1]
 [0 0 0 1 0]
 [0 1 0 0 1]]


### Exemplo 2 - Implementando BOW junto com TF-IDF

In [ ]:
# Importando as Bibliotecas
from sklearn.feature_extraction.text import CountVectorizer
  # classe que transforma os documentos em vetores e realiza a contagem de frequencia
from sklearn.feature_extraction.text import TfidfVectorizer
  # Classe que transforma os documentos em vetores e uma contagem de frequencia ponderada

# Definindo o corpus
documentos = [
    "gato e cachorro",
    "gato brinca com cachorro",
    "gato e rato, cachorro",
    "Cachorro, gato e rato",
    "Gato, cachorro, cachorro",
    "Cachorro e rato"
]

# Criando o modelo BoW
vectorizer_bow = CountVectorizer()
  # Instanciamento da classe em objeto para ser usado
X_bow = vectorizer_bow.fit_transform(documentos)
  # fit >>> realizar a transformação do vocabulário
  # transform >> transforma cada vetor em um documento com a contagem de frequência

# Imprimindo o Vocabulário e a Matriz
print(f"Vocabulário BoW: {vectorizer_bow.vocabulary_}")
print("Matriz BoW:")
print(X_bow.toarray())

# Criando um modelo TF-IDF
vectorizer_tfidf = TfidfVectorizer()
  # realiza a instanciação da classe em objeto
X_tfidf = vectorizer_tfidf.fit_transform(documentos)
  # fit >>> realizar a transformação do vocabulário
  # transform >> transforma cada vetor em um documento com a contagem de frequência ponderada

# Imprimindo o Vocabulário e a Matriz TF-IDF
print(f"\nVocabulário TF-IDF: {vectorizer_tfidf.vocabulary_}")
print("Matriz TF-IDF")
print(X_tfidf.toarray())

Vocabulário BoW: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}
Matriz BoW:
[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 2 0 1 0]
 [0 1 0 0 1]]

Vocabulário TF-IDF: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}
Matriz TF-IDF
[[0.         0.65483184 0.         0.75577461 0.        ]
 [0.63763824 0.28304719 0.63763824 0.32667911 0.        ]
 [0.         0.45813442 0.         0.52875615 0.71451367]
 [0.         0.45813442 0.         0.52875615 0.71451367]
 [0.         0.8661285  0.         0.4998214  0.        ]
 [0.         0.53976033 0.         0.         0.84181874]]


### Exemplo 3 - Realizando o Pre processamento e a Extração de características do texto
Construção de um exemplo de pré-processamento
e representação de texto:
* Limpeza de dados – removendo caracteres indesejados e normalizando o texto.
* Tokenização – dividindo o texto em palavras individuais.
* Remoção de stopwords – eliminando palavras comuns que não carregam significado semântico importante.
* Lematização – reduzindo as palavras à sua forma base.
* Representação de Texto – convertendo o texto processado em uma matriz numérica usando o modelo Bag of Words.

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

documentos = [
    "Os cachorros são animais muito amigáveis e leais!",
    "Eu gosto de gatos porque eles são independentes e fofos.",
    "Cachorros e gatos podem ser ótimos animais de estimaçãos."
]

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words("portuguese"))

def preprocessar_texto(texto):
  texto = re.sub(r'[^a-zA-Zá-ÿ\s]','',texto)
  tokens_tudo = word_tokenize(texto.lower())
  tokens = [palavra for palavra in tokens_tudo if palavra not in stop_words]
  tokens_lema = [lemmatizer.lemmatize(palavra) for palavra in tokens]
  return ' '.join(tokens_lema)

documentos_processados = [preprocessar_texto(doc) for doc in documentos]

print('documentos Pré-processados:')
for i, doc in enumerate(documentos_processados):
  print(f"Documento {i + 1}: {doc}")

vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(documentos_processados)

print("\nVocabulário BoW:", vectorizer.vocabulary_)
print("Matriz BoW:")
print(X_bow.toarray())

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


### Exemplo 4 - WordEmbedding utilizando Word2Vex

In [ ]:
""" Algumas frases para aumentar o corpus:
    ["o","papagaio","está","falando"],
    ["a","lhama","vai","cuspir","em","você"],
    ["o","cachorro","gosta","de","bola"],
"""
# Importação a Biblioteca
from gensim.models import Word2Vec
  # Word2Vec >>> criar os modelos de vetorização

# criação do Corpus
corpus = [
    ["o","cachorro","está","dormindo"],
    ["o","gato","está","dormindo"],
    ["o","cachorro","gosta","de","bola"],
    ["cachorro","gato"],
    ["o","papagaio","está","falando"],
    ["a","lhama","vai","cuspir","em","você"]
]

# Criando o modelo de vetor
model = Word2Vec(sentences=corpus, vector_size=100, window=3, min_count=1,sg=1)
  # sentences = define o texto a ser transformado em vetor
  # vector_size = define a dimensão dos vetores que representarão as palavras
  # window = define a janela de contexto. considera as palavras antes e as palavras depois no alvo para aprender
  # min_count = ignora as palavras que aparecer 1 vez no corpus
  # indica o modelo utilizado
    # 1 = skip_gram;
    # 0 = CBOW

# obtem o vetor da palavra
vector = model.wv['cachorro']

# calcula a similaridade de duas palavras
similarity = model.wv.similarity('cachorro','gato')
  # similaridade cosseno, qt mais próximo de 1, maior similaridade

print("Similaridade entre 'cachorro' e 'gato': ",similarity)

ModuleNotFoundError: No module named 'gensim'

In [ ]:
from gensim.models import Word2Vec

corpus = [
    ["o", "cachorro", "está", "latindo", "no", "quintal"],
    ["o", "gato", "está", "miando", "no", "telhado"],
    ["o", "pássaro", "está", "voando", "no", "céu",'lua'],
    ["a", "bola", "está", "rolando", "no", "chão"],
    ["a", "criança", "está", "brincando", "com", "o", "cachorro"],
    ["o", "gato", "e", "o", "rato", "são", "inimigos"],
    ["a", "água", "está", "quente", "na", "caneca"],
    ["o", "sol", "está", "brilhando", "no", "céu"],
    ["a", "lua", "está", "cheia", "hoje",'no','céu'],
    ["a", "computador", "está", "ligado", "na", "mesa"],
    ['a','lua','esta','no','céu', 'lua','bonita']
]

model = Word2Vec(sentences=corpus, vector_size=100, window=5, min_count=1, sg=1)

# Calculando a similaridade entre palavras
print(f"Similaridade entre cachorro e gato: {model.wv.similarity('cachorro', 'gato')}")
print(f"Similaridade entre cachorro e bola: {model.wv.similarity('cachorro', 'bola')}")
print(f"Similaridade entre céu e lua: {model.wv.similarity('céu', 'lua')}")
print(f"Similaridade entre computador e mesa: {model.wv.similarity('computador', 'mesa')}")

ModuleNotFoundError: No module named 'gensim'